# Generated by Django 4.2.5 on 2024-01-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dateOfBirthday', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('imageProfileURL', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('summary', models.CharField(max_length=500)),
                ('text', models.CharField(blank=True, max_length=2000, null=True)),
                ('likes', models.IntegerField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user', to='app.user')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_topic', to='app.topic')),
            ],
        ),
    ]
