# Generated by Django 4.2.5 on 2024-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_Initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirthday',
            field=models.DateTimeField(),
        ),
    ]
